### ISSUE TITLE
[P.111] 3장 react portal

### ISSUE THREAD

**Issue by lacomparte** [MartinYounghoonKim/front-end-debt#10]
react portal 에서 컴포넌트의 현재 위치와는 상관없이 특정 돔 요소에 랜더링 할 수 있다고 하는데
이런 경우가 어떤 경우인지 궁금합니다.

react 가 root 로 잡는 DOM 말고 
document 내의 있는 아무 DOM 에도 랜더링이 가능한건지..

**Comment by Junkim93** [comment]
보통 저런 기능은 모달 같은 것에 사용하는 경우가 많아요.
잘아시다시피 포지션 absolute인 엘리먼트는 부모 엘리먼트에 영향을 받는데,
어떤 특정 엘리먼트의 하위에 모달 컴포넌트가 속하게 되면 스타일 설정이라던지 이런게 힘들어지니까
저런 기능을 구현하는 것으로 알고있습니다.

그래서 애초에 루트 레벨(가장 최상위의 엘리먼트)에서 해당 모달 컴포넌트를 불러놓고,
모달 컴포넌트의 상태를 전역적으로 관리해서 보여줄지 말지를 결정하거나
portal 같은 기능을 사용하구 있어요!

이상한 코드를 추가하지 않는 이상 react root 태그 안에 모든 태그가 속해있으니까, 모든 엘리먼트로 특정지을 수 있다고 할 수 있을것 같습니다. 다만 SSR의 경우는 정확히 모르겠어요

**Comment by lacomparte** [comment]
> 보통 저런 기능은 모달 같은 것에 사용하는 경우가 많아요.
> 잘아시다시피 포지션 absolute인 엘리먼트는 부모 엘리먼트에 영향을 받는데,
> 어떤 특정 엘리먼트의 하위에 모달 컴포넌트가 속하게 되면 스타일 설정이라던지 이런게 힘들어지니까
> 저런 기능을 구현하는 것으로 알고있습니다.
> 
> 그래서 애초에 루트 레벨(가장 최상위의 엘리먼트)에서 해당 모달 컴포넌트를 불러놓고,
> 모달 컴포넌트의 상태를 전역적으로 관리해서 보여줄지 말지를 결정하거나
> portal 같은 기능을 사용하구 있어요!
> 
> 이상한 코드를 추가하지 않는 이상 react root 태그 안에 모든 태그가 속해있으니까, 모든 엘리먼트로 특정지을 수 있다고 할 수 있을것 같습니다. 다만 SSR의 경우는 정확히 모르겠어요

SSR도 그럼 서버에서 정적 html 을 브라우저에 뿌려주면
리액트 root DOM 이 뿌려줄테니..
저는 CSR이랑 마찬가지인것 같다라는 의견입니다 ㅋㅋ

아래와 같을때 Component 에서 modal 조작이 가능하시다는 말씀이죠?
```react
<div>
  <div>
    <Component />
  </div>
</div>
<Modal>
```
