### ISSUE TITLE
[P.121] 리액트가 비동기로 상탯값을 처리하는 이유는?

### ISSUE THREAD

**Issue by lacomparte** [MartinYounghoonKim/front-end-debt#11]
코드 3-22
```javascript
function MyComponent() {
  const [count, setCount] = useState({ value: 0 });
  function onClick() {
    setCount({value: count.value + 1});
    setCount({value: count.value + 1});
  }
  ...
}
```

여기서 setCount 가 두번 호출되는데 이때 비동기로 처리하기 때문에 count.value 가 모두 0인건가요?

**Comment by Junkim93** [comment]
count.value는 1이 되지 않나요?
이 부분 배치 처리한다는게 코드레벨에서 어떻게 처리되는지가 저도 궁금하네요

비동기로 처리하는 이유는 콜백함수로 상태값 변경을 일괄적으로 처리해야 하기 때문인것 같습니다(?: 이 부분 추측이라 잘 아시는분이 있으면 설명 부탁드리겠습니다 ... )

DOM을 조작하는 코드가 실행되는 순간 브라우저의 Render Tree가 재생성 되는데요.
이렇게 코드마다 Render Tree를 다시 그리면 성능상 안좋으니까
가상 DOM은 DOM을 조작하는 코드를 모아서 일괄 처리 한 다음에 Render Tree를 재생성 하거든요.
상태 값을 변경한다는건 DOM node의 내용을 변경시키는 일이고,
이게 동기적으로 동작한다면 코드가 실행될때마다 화면을 다시 그리게 될테니까
아마 이 일괄적인 처리를 위해서 비동기 형태로 동작하는게 아닌가 싶습니다...?

**Comment by lacomparte** [comment]
> count.value는 1이 되지 않나요?
> 이 부분 배치 처리한다는게 코드레벨에서 어떻게 처리되는지가 저도 궁금하네요
> 
> 비동기로 처리하는 이유는 콜백함수로 상태값 변경을 일괄적으로 처리해야 하기 때문인것 같습니다(?: 이 부분 추측이라 잘 아시는분이 있으면 설명 부탁드리겠습니다 ... )
> 
> DOM을 조작하는 코드가 실행되는 순간 브라우저의 Render Tree가 재생성 되는데요.
> 이렇게 코드마다 Render Tree를 다시 그리면 성능상 안좋으니까
> 가상 DOM은 DOM을 조작하는 코드를 모아서 일괄 처리 한 다음에 Render Tree를 재생성 하거든요.
> 상태 값을 변경한다는건 DOM node의 내용을 변경시키는 일이고,
> 이게 동기적으로 동작한다면 코드가 실행될때마다 화면을 다시 그리게 될테니까
> 아마 이 일괄적인 처리를 위해서 비동기 형태로 동작하는게 아닌가 싶습니다...?

넵 클릭 후 value 는 1이 맞습니다.
클릭 전 value 가 모두 0인 것인가에 대한 물음이였습니다ㅎㅎ
