### ISSUE TITLE
[P.122] 상탯값 변경 함수의 호출 순서대로 상탯값이 변경되기 때문에 result 는 항상 참이다.

### ISSUE THREAD

**Issue by lacomparte** [MartinYounghoonKim/front-end-debt#12]
직접 코드 작성해보니
result 가 false 인것 같은데..

제가 뭘 잘못한걸까요?
그리고 왜 count2 는 첫번째 클릭시 +2가 되는거죠;
https://codesandbox.io/s/p121-hocul-sunseoga-bojangdoeneun-sangtaesgabs-byeongyeong-hamsu-oxg50?file=/src/App.js

**Comment by Junkim93** [comment]
onClick 함수 바디의 두번째 라인에서 같은 변수에 +1 하셔서 그렇습니다 ...!

**Comment by lacomparte** [comment]
> onClick 함수 바디의 두번째 라인에서 같은 변수에 +1 하셔서 그렇습니다 ...!

앗..................
