### ISSUE TITLE
[P.126] removeAddEventListener 는 언제 선언해야 하나요,,?

### ISSUE THREAD

**Issue by lacomparte** [MartinYounghoonKim/front-end-debt#13]
addeventlistener 후 언제 remove 를 시켜줘야 하는지
잘 모르겠습니다.
바로 하면 이벤트가 바로지워지는데..@_@

**Comment by Junkim93** [comment]
p126 설명처럼 useEffect 안에서 리턴 값을 함수로 하고 함수 바디에 해당 이벤트 코드를 호출하면,
자동으로 컴포넌트가 사라지기 직전에 호출되는 것 같습니다.

**Comment by lacomparte** [comment]
> p126 설명처럼 useEffect 안에서 리턴 값을 함수로 하고 함수 바디에 해당 이벤트 코드를 호출하면,
> 자동으로 컴포넌트가 사라지기 직전에 호출되는 것 같습니다.

다시 읽어보니
책에 자세히 나와 있네요..
하하하하하하
