### ISSUE TITLE
[P.170] 의존성 배열을 잘못 관리하면 생기는 일

### ISSUE THREAD

**Issue by lacomparte** [MartinYounghoonKim/front-end-debt#22]
value2 가 변경돼도 부수 효과 함수가 실행되는건 어떻게 봐야 할까요?
https://codesandbox.io/s/serene-bash-ox5k8?file=/src/App.js

요기서 'value2 증가' 버튼 누른 후 'value1 증가' 버튼 누르면
console 에 둘다 1로 찍혀서요;
의존성 배열에 value2 가 없는데..의문입니다..!

**Comment by feel5ny** [comment]
- value2가 변경되어도 의존성 배열에 없어서 useEffect는 실행되지 않는거 같습니다. 
- value2증가 버튼을 누르면, useState훅의 setValue2가 실행되는거라, 상태값 변경이 진행되서 value2는 1이 되고,
- 그 이후에 value1증가를 누르면 
	1. value1 증가 (value1은 1이됨)
	2. useEffect의 반환함수 호출, 
	3. 부수효과함수실행 -> 이시점에 console에 찍히는 값은 둘다 1일듯 합니다.
