### ISSUE TITLE
[p.273] 값에 의한 호출과 참조에 의한 호출

### ISSUE THREAD

**Issue by feel5ny** [MartinYounghoonKim/front-end-debt#28]
기초질문같...ㅎ
6-35 코드가 이해가 잘 안가네요ㅜ
```js
[REMOVE]: (state, action) => {
	state = state.filter(item => item.id !== action.item.id);
}
```
> 순간적으로 매개변수의 값만 변경될 뿐이다.

```js
// 코드 6-36
function myFunc(a){
	a = 20;
}
let v = 10;
myFunc(v);
console.log(v)
```
6-36에서 값만변경되고 v는 변하지 않는 부분은 알겠는데, 
6-35코드는 filter하면 새로운 배열을 반환해줘서 호출때마다 state의 주소값이 달라지는거 아닌가요?_?

**Comment by lacomparte** [comment]
저도요!!
이해가 잘 안갑니다-_-;

**Comment by feel5ny** [comment]
- [누군가 해당사항 이슈 제기](https://github.com/landvibe/book-react/issues/15)
- [저자가 수정한 내역](https://github.com/landvibe/book-react/blob/master/corrections.md#%EC%9C%84%EC%B9%98-p273-%EA%B8%80%EC%83%81%EC%9E%90)

음..!? 그렇다네요..!

**Comment by ritaru** [comment]
Call-by-value의 경우 오브젝트를 불러오는 것이 아닌, 오브젝트의 복사본을 가져오는 것이기 때문에 매개변수의 값을 수정(6-35에서 state = state.filter(...))한다고 해서 변하지 않는다는 의미입니다.

이 경우 매개변수의 reference가 변하긴 하지만, Call-by-reference가 아니기 때문에 원본 오브젝트는 변하지 않는 게 되죠.
모든 Call-by-value 컨벤션에서의 매개변수는 "원본의 Hard Copy" 임을 생각하시면 쉬울 것 같네요.
