### ISSUE TITLE
발표주제

### ISSUE THREAD

**Issue by MartinYounghoonKim** [MartinYounghoonKim/front-end-debt#3]
CSS in JS - 상락님, 7장 - 마틴님, 현석님 (2주)

3장 -  새기님, 신영님, 상락님 (3주)
4장 - 병진님,  (1주)
5장 - 애희님, 은정님 ( 2주)
6장 - 현준님, 리타 (2~ 3주)

**Comment by hyunjunkim-93** [comment]
영훈님 대충 정리해봤어요

## 모임
- 교재: 실전 리액트 프로그래밍
- 일정: 매주 수요일 오후 6시 30분 - ?
- 장소: 코로나 진정시까지 온라인

## 진행 상황
### 이번주
```
- 이번주 진행자
  - CSS in JS (상락님)
  - 7장 웹팩, 바벨 심화 (마틴님, 현석님)
```

### 진행 예정
- 3장: 새기님, 신영님, 상락님 (3주)
- 4장: 병진님, (1주)
- 5장: 애희님, 은정님 ( 2주)
- 6장: 현준님, 리타 (2~ 3주)

### 완료
- 201209: 1장, 모듈 시스템
- 201216:
- 201223:
- 201230:

## 이슈 공유
```
- 레파지토리 내 issues 탭 활용
  - 포맷 예시: [Sample P.16] 1장. 1.1 리액트는 뭔가요?
```

**Comment by MartinYounghoonKim** [comment]
@hyunjunkim-93 https://github.com/MartinYounghoonKim/front-end-debt/wiki/Study-information 옮겼습니다. 감사합니다 ㅎㅎ
