### ISSUE TITLE
[P.328] 7장. babel useBuiltIns: usage 옵션 관련

### ISSUE THREAD

**Issue by lacomparte** [MartinYounghoonKim/front-end-debt#4]
_p. 328_
2번 각주
```javascript
const obj = {
  a: 10,
  b: 20,
}
const arr = Object.values(obj); // [10, 20]
const exist = arr.includes(10) // true
```
일때 babel 이 arr 의 타입을 추론하지 못해서 string.includes polyfill 을 추가했는데
String.prototype.includes(),
Array.prototype.includes()
두 함수 모두 크롬 41버전 이상부터 사용가능한데..
왜 타입이랑 무슨상관인지 그리고 왜 추가된건지 이해가 안됩니다 ㅠ

**Comment by Junkim93** [comment]
적어주신대로 includes 메서드는 `string` 인스턴스와 `array`인스턴스 모두 가지고 있는데요.
코드상에서 우리가 확인할때는 Object.values로 [10, 20]이란 배열을 얻고 이 배열을 arr에 할당했다고 확인할 수 있지만,

바벨이 해당 코드를 변환할때는 마지막 라인에서 arr이란 변수가 `array` 인지 `string`인지 알지를 못합니다.
https://babeljs.io/docs/en/#type-annotations-flow-and-typescript
왜 알지를 못하는지에 관한 정확한 이유는 잘 모르겠네요 😅

제 추측으로는 책 설명대로 자바스크립트는 변수의 타입을 지정하지 않고,
코드가 런타임(브라우저환경이나 node.js에서 실행될때) 평가되고,
바벨이 실행되는 시점은 런타임 이전이기 때문에 함부로 단정지을 수 없어서 그런 것 같아요

반면에 타입스크립트는
``` ts
const str: string = 'string'; // :string -> 변수 str은 string 타입
const numArr: number[] = [10, 20]; // :number[] -> 변수 arr은 Array이며 숫자만 들어갈 수 있음
```
이런식으로 코드를 작성할때 타입을 지정해주거든요.
그래서 바벨이 해당 폴리필을 추가할지 말지 결정할때에도 아 arr은 배열이구나를 알 수 있어서,
어떤 폴리필만 추가해야할지 판단할 수 있다는 말인 것 같습니다.

결론적으로 자바스크립트로 작성했을때는 두 경우를 모두 대비할 수 있게 includes에 관한 폴리필을 전부 추가한 것 같습니다.

**Comment by lacomparte** [comment]
그렇군요..
런타임시 arr 에 어떤 type(string, array)의 변수가 들어올지 모르니까
일단 두개다 넣어놓는 거군요.
감사합니다.

그렇다면
타입스크립트는 보다 번들파일 크기가 줄겠네요.
