### ISSUE TITLE
[P. 337] 7장. lodash 관련

### ISSUE THREAD

**Issue by lacomparte** [MartinYounghoonKim/front-end-debt#5]
_p. 337_

lodash 를 사용하는 부분이 있는데
babel 과 마찬가지로 몽땅 다 가져오면 번들크기가 커질것 같은데..
lodash 는 사용하는것 하나하나 각 module 에서 import 를 해야 하는건가요?

**Comment by Junkim93** [comment]
lodash는 모듈화가 굉장히 잘되어있는데요.
제가 알기로는 크게 두 가지 방법이 있습니다.

첫 번째는 책에서 나온 트리쉐이킹 인데요.
7장 설명을 보시면 나뭇잎 털듯이 안쓰는 코드를 다 떨구는 트리쉐이킹이 나오는데,
이 트리쉐이킹이 알아서 코드를 잘 떨궈줍니다.
근데 책에서도 나오듯이 사용하는쪽, 사용되는 쪽 둘 다 ESM(import나 export 문법 사용하는 자바스크립트 모듈 시스템)을 사용해야 돼요.
그냥 lodash는 ESM으로 작성되어 있지 않아서 lodash-es를 설치해서 사용합니다.
https://github.com/lodash/lodash#module-formats

두 번째는 그냥 필요한 것만 불러오는것인데요.
lodash는 각 함수별로 모듈화되어있어서 그냥 이거 하나하나씩 불러서 사용하는 경우도 있어요 ... !
https://www.npmjs.com/package/lodash.debounce
그래서 그냥
```
npm i --save lodash.debounce
```
``` js
import debounce from 'lodash.debounce';
```
이렇게 사용하는 경우도 있습니다
