### ISSUE TITLE
[P.116] 3장 ReactDOM.render 함수로 전달된 리액트 요소 트리구조

### ISSUE THREAD

**Issue by lacomparte** [MartinYounghoonKim/front-end-debt#8]
ReactDOM.render 함수로 전달된 리액트 요소 트리구조를
브라우저에서 console.log 로 찍어 볼 수 있나요?

**Comment by Junkim93** [comment]
리액트 프로젝트 클론해서 render 하는 부분에 콘솔로그 코드 추가하고,

콘솔로그 코드 추가한 리액트 프로젝트를 불러와서 사용하면 될거같아요 !

**Comment by lacomparte** [comment]
> 리액트 프로젝트 클론해서 render 하는 부분에 콘솔로그 코드 추가하고,
> 
> 콘솔로그 코드 추가한 리액트 프로젝트를 불러와서 사용하면 될거같아요 !

```javascript
ReactDOM.render() // 이 함수 말씀하시는 건가요?
```
