### ISSUE TITLE
[P.117] 3장 ReactDOM.render 함수로 전달된 리액트 요소 트리구조2

### ISSUE THREAD

**Issue by lacomparte** [MartinYounghoonKim/front-end-debt#9]
ReactDOM.render 함수로 전달된 리액트 요소 트리구조에서
트리의 루트는 div 태그로 변경된다고 하는데
무조건 div 인건지.. 아니면 해당 컴포넌트의 parentElement 를 가져와서 넣어주는지 궁금합니다

**Comment by Junkim93** [comment]
이 부분 저도 궁금하네요.
실제로 브라우저에 렌더된 결과물은 사용자가 정의한 태그로 렌더되긴 해요

**Comment by lacomparte** [comment]
> 실제로 브라우저에 렌더된 결과물은 사용자가 정의한 태그로 렌더되긴 해요

맞아요
사용자가 정의한걸로 변경되는데
없으면 div 인건지는 모르겠네요;
